# Generated by Django 5.0.6 on 2024-09-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cor", models.CharField(blank=True, max_length=50, null=True)),
                ("tamanho", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
