# Generated by Django 5.1.1 on 2024-09-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="categorias",
            field=models.ManyToManyField(related_name="produtos", to="core.categoria"),
        ),
    ]
