# Generated by Django 5.1.1 on 2024-09-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_carrinho"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinho",
            name="produtos",
            field=models.ManyToManyField(related_name="produto", to="core.produto"),
        ),
    ]
